version: '3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:

  db:
    container_name: db_postrgre
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend_foodgram
    image: rodichevm/foodgram_backend
    restart: always
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    container_name: frontend_foodgram
    image: rodichevm/foodgram_frontend
    volumes:
      - ../frontend/:/frontend/result_build/
    depends_on:
      - db

  nginx:
    container_name: nginx_foodgram
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
