version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:

  db:
    container_name: db_foodgram
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend_foodgram
    build: ./backend/foodgram/
    volumes:
      - static_value:/backend_static
      - media_value:/media/
    env_file: .env
    depends_on:
      - db

  frontend:
    container_name: frontend_foodgram
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_value:/frontend_static
    env_file: .env
    depends_on:
      - backend

  gateway:
    container_name: gateway_foodgram
    build: ./infra/
    volumes:
      - static_value:/staticfiles/
      - media_value:/media/
    env_file: .env
    ports:
      - "8000:80"
    depends_on:
      - frontend
