version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:

  db:
    container_name: db_foodgram
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend_foodgram
    image: rodichevm/foodgram_backend
    volumes:
      - static_value:/backend_static
      - media_value:/media/
    depends_on:
      - db
    env_file: .env

  frontend:
    container_name: frontend_foodgram
    image: rodichevm/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_value:/frontend_static
    env_file: .env
    depends_on:
      - backend

  gateway:
    container_name: gateway_foodgram
    image: rodichevm/foodgram_gateway
    ports:
      - 7000:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_value:/staticfiles/
      - media_value:/media/
    depends_on:
      - frontend
