version: '3.8'

volumes:
  postgres_data:
  static_value:
  media_value:

services:

  db:
    container_name: db_postrgre
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend_foodgram
    image: rodichevm/foodgram_backend
    env_file: .env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    restart: always

  frontend:
    container_name: frontend_foodgram
    image: rodichevm/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /app/static/
    volumes:
      - static_value:/app/static/

  nginx:
    container_name: nginx_foodgram
    image: nginx:1.19.3
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend