  name: Foodgram workflow
  on: push

  jobs:
    tests:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [ "3.8", "3.9", "3.10" ]

      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 flake8-isort
            cd backend/foodgram
            pip install -r requirements.txt
        - name: Test with flake8
          run: |
            python -m flake8

    build_backend_and_push_to_docker_hub:
      name: Push backend Docker image to DockerHub
      runs-on: ubuntu-latest
      needs: tests
      if: github.ref_name == 'main'
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/foodgram
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest

    build_frontend_and_push_to_docker_hub:
      name: Push frontend Docker image to DockerHub
      runs-on: ubuntu-latest
      needs: tests
      if: github.ref_name == 'master'
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest


  
